security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Customer
        property: name

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      provider: app_user_provider
      form_login: ~
      logout: ~
  
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
